# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Likelihood cross-validation for kernel density estimation with MIG
#' 
#' Given a data matrix over a half-space defined by \code{beta},
#' compute the log density using leave-one-out cross validation,
#' taking in turn an observation as location vector and computing the 
#' density of the resulting mixture.
#' @inheritParams dmig
#' @return the value of the likelihood cross-validation criterion
#' @export
mig_lcv <- function(x, beta, Omega) {
    .Call(`_mig_mig_lcv`, x, beta, Omega)
}

